/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const { nodes, materials } = useGLTF('/HeadYaw.glb')
  
   return [{type: 'group' , children : [{type : 'raw', geometry:nodes.HeadYaw.geometry , material:materials['shiny_white.002'], scale : 0.01}]}]
      
  
}

useGLTF.preload('/HeadYaw.glb')
