/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/HipRoll.glb')
  return [{
    type: 'group', children: [{
      type: 'raw', geometry: nodes.HipRoll.geometry, material: materials['shiny_white.004'], scale: 0.01
    }]
  }]



}

useGLTF.preload('/HipRoll.glb')
