/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/HipRoll.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.HipRoll.geometry} material={materials['shiny_white.004']} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/HipRoll.glb')
