/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import Link2 from './link2.glb';

export default function Model(props) {
  const { nodes, materials } = useGLTF(Link2);
  return [{type:'raw',geometry:nodes.node0.geometry, material:materials.Part__Feature024}]




}

useGLTF.preload(Link2)
