/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei';
import Link3 from './link3.glb';

export default function Model(props) {

  const { nodes, materials } = useGLTF(Link3);
  return [{  type:'raw',
    geometry:nodes.node0_001.geometry,
    material:materials.Part__Feature_001_001_001_002,
    position:[0, -0.12, 0]},
    {type:'raw',
    geometry:nodes.node1.geometry,
    material:materials.Part__Feature001_010_001_002,
    position:[0, -0.12, 0]},
    {type:'raw',
    geometry:nodes.node2.geometry,
    material:materials.Part__Feature002_007_001_002,
    position:[0, -0.12, 0]},
    {  type:'raw',
      geometry:nodes.node3.geometry,
      material:materials.Part__Feature003_004_001_002,
      position:[0, -0.12, 0]}]
}

useGLTF.preload(Link3)
