/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes } = useGLTF('/camera_visor.glb')

  return [{ type: 'group', children: [{ type: 'raw', geometry: nodes.camera_visor.geometry, material: nodes.camera_visor.material }]}]
}

useGLTF.preload('/camera_visor.glb')
