/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const { nodes } = useGLTF('/camera_base.glb')


  return [{ type: 'group', children: [{ type: 'raw', geometry: nodes.camera_base.geometry, material: nodes.camera_base.material }] }]


}

useGLTF.preload('/camera_base.glb')
