/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const { nodes} = useGLTF('/HeadYaw.glb')
  return [{type : 'group',children : [{type:'raw' ,geometry : nodes.HeadYaw_010.geometry , material : nodes.HeadYaw_010.material}]}]
    
     
  
}

useGLTF.preload('/HeadYaw.glb')
