/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const { nodes } = useGLTF('/HeadPitch_0.10.glb')

  return [{ type: 'group', children: [{ type: 'raw', geometry: nodes.HeadPitch_010.geometry, material: nodes.HeadPitch_010.material }] }]



}

useGLTF.preload('/HeadPitch_0.10.glb')
