/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const { nodes, materials } = useGLTF('/HipPitch.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.HipPitch_010.geometry , material : nodes.HipPitch_010.material }]
  }]


  
      
   
}

useGLTF.preload('/HipPitch.glb')
