/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/HipRoll.glb')
  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.HipRoll_010.geometry , material: nodes.HipRoll_010.material }]
  }]


     
 
}

useGLTF.preload('/HipRoll.glb')
