/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/KneePitch.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.KneePitch_010.geometry , material  :nodes.KneePitch_010.material  }]
  }]



      
   
}

useGLTF.preload('/KneePitch.glb')
