/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/LElbowYaw.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.LElbowYaw_010.geometry, material : nodes.LElbowYaw_010.material }]
  }]


  
   
    
}

useGLTF.preload('/LElbowYaw.glb')
