/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/LElbowRoll.glb')
  
  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.LElbowRoll_010.geometry , material : nodes.LElbowRoll_010.material }]
  }]


  
    
  
}

useGLTF.preload('/LElbowRoll.glb')
