/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/LFinger21.glb')
  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.LFinger21_010.geometry,  material : nodes.LFinger21_010.material}]
  }]

     
    
}

useGLTF.preload('/LFinger21.glb')
