/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/LFinger11.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.LFinger11_010.geometry , material : nodes.LFinger11_010.material }]
  }]
}

  
    
    


useGLTF.preload('/LFinger11.glb');
