/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/LFinger43.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.LFinger43_010.geometry, material : nodes.LFinger43_010.material
  }]
  }]


  
    
}

useGLTF.preload('/LFinger43.glb')
