/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/LFinger12.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.LFinger12_010.geometry , material : nodes.LFinger12_010.material }]
  }]



 
      
    
}

useGLTF.preload('/LFinger12.glb')
