/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/LFinger32.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.LFinger32_010.geometry , material : nodes.LFinger32_010.material}]
  }]


  
  
    
}

useGLTF.preload('/LFinger32.glb')
