/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/LFinger33.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.LFinger33_010.geometry , material : nodes.LFinger33_010.material }]
  }]


  

    
}

useGLTF.preload('/LFinger33.glb')
