/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
 
  const { nodes, materials } = useGLTF('/LShoulderPitch.glb')
  
  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.LShoulderPitch_010.geometry, material : nodes.LShoulderPitch_010.material }]
  }]


     
    
}

useGLTF.preload('/LShoulderPitch.glb')
