/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/LShoulderRoll.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.LShoulderRoll_010.geometry , material : nodes.LShoulderRoll_010.material }]
  }]


  
      
    
}

useGLTF.preload('/LShoulderRoll.glb')
