/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/LShoulderPitch.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.LShoulderPitch_010.geometry} material={nodes.LShoulderPitch_010.material} />
    </group>
  )
}

useGLTF.preload('/LShoulderPitch.glb')
