/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/LThumb2.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.LThumb2_010.geometry, material : nodes.LThumb2_010.material }]
  }]  
}

useGLTF.preload('/LThumb2.glb')
