/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {

  const { nodes, materials } = useGLTF('/LThumb1.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.LThumb1_010.geometry, material : nodes.LThumb1_010.material}]
  }]


  
     
    
}

useGLTF.preload('/LThumb1.glb')
