/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/LWristYaw.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry: nodes.LWristYaw_010.geometry, material : nodes.LWristYaw_010.material
  }]
  }]


  
     
}

useGLTF.preload('/LWristYaw.glb')
