/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RElbowYaw.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RElbowYaw_010.geometry, material : nodes.RElbowYaw_010.material }]
  }]


 
     
   
}

useGLTF.preload('/RElbowYaw.glb')
