/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RElbowRoll.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.RElbowRoll_010.geometry, material : nodes.RElbowRoll_010.material }]
  }]


  
     
   
}

useGLTF.preload('/RElbowRoll.glb')
