/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RFinger32.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RFinger32_010.geometry, material : nodes.RFinger32_010.material }]
  }]

       
}

useGLTF.preload('/RFinger32.glb')
