/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RFinger12.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RFinger12_010.geometry, material : nodes.RFinger12_010.material }]
  }]


  
 
    
}

useGLTF.preload('/RFinger12.glb')
