/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RFinger11.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.RFinger11_010.geometry, material : nodes.RFinger11_010.material }]
  }]


 
     
   
}

useGLTF.preload('/RFinger11.glb')
