/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/RFinger43.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RFinger43_010.geometry, material : nodes.RFinger43_010.material }]
  }]


  
      
    
}

useGLTF.preload('/RFinger43.glb')
