/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RFinger41.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.RFinger41_010.geometry, material : nodes.RFinger41_010.material }]
  }]


  
     
    
}

useGLTF.preload('/RFinger41.glb')
