/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/RFinger21.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.RFinger21_010.geometry,  material : nodes.RFinger21_010.material}]
  }]


 
     
    
}

useGLTF.preload('/RFinger21.glb')
