/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RFinger42.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.RFinger42_010.geometry, material : nodes.RFinger42_010.material}]
  }]


 
    
   
}

useGLTF.preload('/RFinger42.glb')
