/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/RShoulderRoll.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RShoulderRoll_010.geometry, material : nodes.RShoulderRoll_010.material }]
  }]

  
      
   
}

useGLTF.preload('/RShoulderRoll.glb')
