/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RShoulderPitch.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.RShoulderPitch_010.geometry , material : nodes.RShoulderPitch_010.material}]
  }]


  
     
   
}

useGLTF.preload('/RShoulderPitch.glb')
