/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/RThumb2.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.RThumb2_010.geometry, material : nodes.RThumb2_010.material}]
  }]


 
  
    
}

useGLTF.preload('/RThumb2.glb')
