/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
 
  const { nodes, materials } = useGLTF('/RThumb1.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RThumb1_010.geometry, material : nodes.RThumb1_010.material }]
  }]

 

    
}

useGLTF.preload('/RThumb1.glb')
