/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const { nodes, materials } = useGLTF('/RWristYaw.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.RWristYaw_010.geometry, material : nodes.RWristYaw_010.material }]
  }]

 
  
    
}

useGLTF.preload('/RWristYaw.glb')
