/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/t265.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.t265.geometry, material : nodes.t265.material}]
  }]


 
      
    
}

useGLTF.preload('/t265.glb')
