/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/Torso.glb')

  return [{
    type : 'group', children : [{type : 'raw' , geometry : nodes.Torso_010.geometry, material : nodes.Torso_010.material }]
  }]

  
     
}

useGLTF.preload('/Torso.glb')
