/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  
  const { nodes, materials } = useGLTF('/WheelB.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,  geometry : nodes.WheelB_010.geometry, material : nodes.WheelB_010.material
  }]
  }]


  
     
}

useGLTF.preload('/WheelB.glb')
