/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/WheelFR.glb')

  return [{
    type : 'group', children : [{type : 'raw' ,geometry : nodes.WheelFR_010.geometry, material : nodes.WheelFR_010.material }]
  }]


  
     
}

useGLTF.preload('/WheelFR.glb')
